// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `picoframe-prdownloader:default`.
const COMMANDS: &[&str] = &["prd_version", "prd_repos", "prd_versions", "prd_download"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
