// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case -> kebab-case),
// which `permissions/default.toml` aggregates into `worker:default`.
const COMMANDS: &[&str] = &["worker_status", "worker_crunch"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
